#	Makefile
#	Objetivo exibir uma mesagem Ola Mundo
#
#
#
#
#

all:	mensagem1
		@echo "Ola galera do Canal Geofisicando"

mensagem1:
		@echo "	Ola sou a mensagem 1"

mensagem2:
		@echo "Ola sou a mensagem 2"

criardiretorio:
		mkdir diretorio
